# Generated by Django 4.0.2 on 2022-02-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Chatservice',
        ),
    ]
