# Generated by Django 4.0.2 on 2022-03-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessionalprofile',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
